name: üçè iOS Builds
on:
  push:
    branches: [ godot-3.x ]

# Global Settings
env:
  PROJECT_FOLDER: .
  TARGET_PATH: demo/addons/godot-sqlite/bin/ios/
  TARGET_NAME: libgdsqlite
  TARGET: release

jobs:
  ios-compilation:
    name: iOS Compilation
    runs-on: "macos-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      # Use python 3.x release (works cross platform)
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # You can test your matrix by printing the current Python version
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        run: |
          mkdir -v -p ${{env.PROJECT_FOLDER}}/${{env.TARGET_PATH}}/armv7
          mkdir -v -p ${{env.PROJECT_FOLDER}}/${{env.TARGET_PATH}}/arm64
          cd ${{env.PROJECT_FOLDER}}
          cd godot-cpp
          scons platform=ios ios_arch=armv7 bits=64 target=${{env.TARGET}} generate_bindings=yes -j4
          scons platform=ios ios_arch=arm64 bits=64 target=${{env.TARGET}} generate_bindings=yes -j4
          ls bin/
          cd ..
          scons platform=ios ios_arch=armv7 target=${{env.TARGET}} target_path=${{env.TARGET_PATH}} target_name=${{env.TARGET_NAME}}
          scons platform=ios ios_arch=arm64 target=${{env.TARGET}} target_path=${{env.TARGET_PATH}} target_name=${{env.TARGET_NAME}}
          cp godot-cpp/bin/libgodot-cpp.ios.release.arm64.a ${{env.TARGET_PATH}}/arm64/libgodot-cpp.ios.release.arm64.a
          cp godot-cpp/bin/libgodot-cpp.ios.release.armv7.a ${{env.TARGET_PATH}}/armv7/libgodot-cpp.ios.release.armv7.a

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios
          path: ${{env.PROJECT_FOLDER}}/${{env.TARGET_PATH}}
